apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docentre-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docentre-frontend-clusterip
                port:
                  number: 5173
