apiVersion: v1
kind: Service
metadata:
  name: docentre-db-clusterip
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: docentre-app-clusterip # the frontend endpoint to connect backend is docentre-app-clusterip
spec:
  type: ClusterIP
  selector:
    app: docentre-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: docentre-ui-clusterip
# spec:
#   type: ClusterIP
#   selector:
#     app: docentre-ui
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000
